# -*- coding: utf-8 -*-
"""ENA_Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i8LY95hCwqbk4fcmAK12YT0lxH5TDzrW
"""

# !pip install gymnasium[classic-control]

def make_env(gravity=-9.8, mass_pole=0.1, pole_length=0.5, render_mode=None):
	import gymnasium as gym
	env = gym.make("CartPole-v1", render_mode=render_mode)

	# Physics Parameters
	env.unwrapped.gravity = gravity
	env.unwrapped.length = pole_length # half-length
	env.unwrapped.masspole = mass_pole

	# Recalculate all internal dependencies used by the physics engine
	env.unwrapped.total_mass = env.unwrapped.masspole + env.unwrapped.masscart
	env.unwrapped.polemass_length = env.unwrapped.masspole * env.unwrapped.length

	# ADD THIS: Some versions of Gym use this specific variable name in step()
	if hasattr(env.unwrapped, "masspole_length"):
		env.unwrapped.masspole_length = env.unwrapped.masspole * env.unwrapped.length

	return env

def play(agent, environments, episodes_per_env, threshold=475.0):
	history = []
	for env_idx, env in enumerate(environments):
		for episode in range(episodes_per_env[env_idx]):
			state, _ = env.reset()
			state = np.array(state, dtype=np.float32)
			episode_score = 0
			is_done = False

			while not is_done:
				# 1. Agent performs the step internally
				# Returns: (next_state, reward, done, action)
				next_state, reward, terminated, truncated, action = agent.act(env, state)
				is_done = terminated or truncated

				# 2. Collect data for training (DQN uses this per-step, ENA uses this later)
				if agent.learn:
					agent.train(
						env,
						{
							"action": action,
							"done": is_done,
							"next_state": next_state,
							"reward": reward,
							"state": state,
						},
					)

				episode_score += reward
				state = next_state

			history.append({
				"env_id": env_idx,
				"episode": len(history) + 1,
				"score": episode_score,
				"specialist_id": getattr(agent, "best_individual_idx", 0),
			})
	return pd.DataFrame(history)

# General imports
import random
import uuid

# Libs imports
import numpy as np
import tensorflow as tf
from collections import deque
from numpy.linalg import norm
from tensorflow.keras import Sequential, Input
from tensorflow.keras.layers import Dense

class ENAgent:
	def __init__(
		self,
		action_size,
		state_shape,
		exploration_rate=0.20,
		history_size=100,
		gladiator_amounts=5,
		plasticity_algorithm="zero",
		pop_size=30,
		mutation_rate=0.01,
		trust_algorithm="zero",
	):
		self.action_size = action_size
		self.exploration_rate = exploration_rate
		self.last_episode_score = 0
		self.learn = True
		self.mutation_rate = mutation_rate
		self.plasticity_algorithm = plasticity_algorithm
		self.plasticity_history = []
		self.pop_size = pop_size
		self.state_shape = state_shape
		self.trust_algorithm = trust_algorithm

		# AGNOSTIC STATISTICS
		self.reward_history = deque(maxlen=history_size)
		self.max_seen = -np.inf
		self.min_seen = np.inf
		self.episodes_seen = 0

		# Hall of Fame
		self.gladiator_amounts = gladiator_amounts
		self.hall_of_fame = {}

		# Initialize population with age and score metadata
		self.best_individual_idx = 0
		self.current_episode_reward = 0
		self.population = [self.__build_individual() for _ in range(pop_size)]

	def act(self, env, state):
		# 1. Selection Logic
		# We only pick a NEW specialist at the very start of an episode
		# (when current_episode_reward is 0)
		if self.current_episode_reward == 0:
			if self.learn and np.random.rand() < self.exploration_rate:
				self.best_individual_idx = np.random.randint(self.pop_size)
			else:
				trust_scores = [guy["trust"] for guy in self.population]
				self.best_individual_idx = np.argmax(trust_scores)

		# 2. Execution
		chosen = self.population[self.best_individual_idx]
		q_values = chosen["model"](state.reshape(1, -1), training=False)
		action = np.argmax(q_values.numpy()[0])

		next_state, reward, terminated, truncated, _info = env.step(action)
		done = terminated or truncated

		# 3. Internal State Management
		self.current_episode_reward += reward

		# 4. EPISODE OVER: Update trust autonomously
		if done:
			self.last_episode_score = self.current_episode_reward

			if not self.learn:
				decay = self.__get_trust_decay(self.last_episode_score)
				old_trust = self.population[self.best_individual_idx]["trust"]
				# Apply the penalty/decay
				# If decay is 1.0 (failure), trust drops INSTANTLY to the low score
				new_trust = (1 - decay) * old_trust + (decay * self.last_episode_score)
				self.population[self.best_individual_idx]["trust"] = new_trust

			self.current_episode_reward = 0 # Reset for next episode

		return next_state, reward, terminated, truncated, action

	def load_gladiators(self):
		"""Re-introduces the Gladiators into the active population."""
		if not self.hall_of_fame:
			return
		print(f"   >>> Loading {len(self.hall_of_fame)} Gladiators.")

		# Convert dict values to list
		gladiators = list(self.hall_of_fame.values())
		for index, gladiator in enumerate(gladiators):
			if index >= self.pop_size: break

			# Overwrite population slot
			target = self.population[index]
			target["age"] = 0
			target["id"] = gladiator["id"]
			target["model"].set_weights(gladiator["model"].get_weights())
			target["trust"] = self.__get_dynamic_ref_trust()

	def set_learning(self, mode):
		"""Reset trust"""
		self.learn = mode
		for guy in self.population:
			guy["trust"] = self.__get_dynamic_ref_trust()
			guy["age"] = 0
		self.best_individual_idx = 0

	def train(self, env, step_data):
		"""Handles the evolutionary search."""
		# Only evolve at the end of an episode
		if not step_data["done"]:
			return

		# 1. Update Global Statistics
		self.episodes_seen += 1
		self.reward_history.append(self.last_episode_score)
		if self.last_episode_score > self.max_seen: self.max_seen = self.last_episode_score
		if self.last_episode_score < self.min_seen: self.min_seen = self.last_episode_score

		# 2. Calculate the "Failure Signal" (Decay) ONCE
		# This value is 0.1 if performing well, and 1.0 if failing.
		failure_signal = self.__get_trust_decay(self.last_episode_score)

		# 3. Update the current Specialist's Trust
		chosen = self.population[self.best_individual_idx]
		old_trust = chosen["trust"]
		chosen["trust"] = (
			(1 - failure_signal) * old_trust + (failure_signal * self.last_episode_score)
		)

		# 4. Trigger Global Reset (Forget old winners)
		# We use the same failure_signal. If it's high (> 0.1), we reset everyone.
		if failure_signal > 0.1:
			self.__update_hall_of_fame(chosen, old_trust)
			self.__reset_trust(factor=failure_signal)

		# 5. Evaluate others based on Plasticity
		plasticity = self.__get_plasticity(self.last_episode_score)
		self.plasticity_history.append(plasticity)

		num_to_eval = max(2, int(self.pop_size * plasticity))
		other_indices = [
			index for index in range(self.pop_size) if index != self.best_individual_idx
		]
		test_indices = random.sample(other_indices, min(len(other_indices), num_to_eval))

		gen_seed = np.random.randint(0, 9999)
		for idx in test_indices:
			guy = self.population[idx]
			guy["trust"] = self.__evaluate_individual_performance(guy["model"], env, seed=gen_seed)
			guy["age"] += 1

		# 6. Breed and Mutate
		self.__evolve_population()

		# 7. Final selection for the next training episode
		trusts = [guy["trust"] for guy in self.population]
		self.best_individual_idx = np.argmax(trusts)

	# Private methods
	def __build_individual(self):
		"""Build the NN model"""
		initializer = tf.keras.initializers.Orthogonal(gain=1.0)
		model = Sequential([
			Input(shape=self.state_shape),
			Dense(4, activation="relu", kernel_initializer=initializer),
			Dense(2, activation="relu", kernel_initializer=initializer),
			Dense(self.action_size, activation="linear", kernel_initializer=initializer)
		])
		return {
			"age": 0,
			"id": str(uuid.uuid4()),
			"model": model,
			"trust": self.__get_dynamic_ref_trust(),
		}

	def __calculate_genetic_similarity(self, ind_a, ind_b_record):
		"""
		Calculates the Cosine Similarity between a candidate and a HoF record.
		Returns: float between -1.0 (opposite) and 1.0 (identical)
		"""
		# 1. Extract and Flatten Weights
		# Candidate is a live dictionary, HoF record is a stored dictionary
		weights_a = ind_a["model"].get_weights()
		weights_b = ind_b_record["model"].get_weights()

		# Flatten list of arrays into a single 1D vector
		vec_a = np.concatenate([w.flatten() for w in weights_a])
		vec_b = np.concatenate([w.flatten() for w in weights_b])

		# 2. Compute Cosine Similarity: (A . B) / (|A| * |B|)
		# A value of 1.0 means they are genetically identical strategies
		dot_product = np.dot(vec_a, vec_b)
		norm_a = norm(vec_a) + 1e-8
		norm_b = norm(vec_b) + 1e-8

		similarity = dot_product / (norm_a * norm_b)
		return similarity

	def __crossover(self, p1, p2):
		"""Crossover method"""
		child = self.__build_individual()
		w1, w2 = p1["model"].get_weights(), p2["model"].get_weights()
		new_weights = []
		for weight1, weight2 in zip(w1, w2):
			mask = np.random.random(weight1.shape) < 0.5
			combined = np.where(mask, weight1, weight2)
			new_weights.append(combined)
		child["model"].set_weights(new_weights)
		child["age"] = max(p1["age"], p2["age"])
		return child

	def __get_dynamic_ref_trust(self):
		"""Replaces ref_trust. Uses the moving average of performance."""
		if len(self.reward_history) < 5: return 0.0
		return np.mean(self.reward_history)

	def __evaluate_individual_performance(self, individual_model, env, seed=None):
		"""
		Helper method to run a single episode for a given individual's model
		and return its score.
		"""
		state, _ = env.reset(seed=seed)
		done, score = False, 0
		while not done:
			action = individual_model(state.reshape(1, -1), training=False)
			state, reward, terminated, truncated, _ = env.step(np.argmax(action.numpy()[0]))
			done = terminated or truncated
			score += reward
		return float(score)

	def __evolve_population(self):
		"""Evolution method that preserves individual IDs and guarantees diversity space."""
		# 1. Rank indices by trust/performance to find who to keep and who to kill
		indices = list(range(self.pop_size))
		indices.sort(
			key=lambda index: (self.population[index]["trust"], self.population[index]["age"]),
			reverse=True,
		)

		# 2. Define our "Strategy Budget" for the whole population
		# Example: 20% Elites, 30% Mutants, 30% Crossovers, 20% Fresh
		elite_count = max(2, int(self.pop_size * 0.2))
		mutant_count = int(self.pop_size * 0.3)
		crossover_count = int(self.pop_size * 0.3)
		# The rest will be Fresh individuals (approx 20%)

		elite_indices = indices[:elite_count]
		# Everyone else is a candidate for replacement
		to_replace_indices = indices[elite_count:]

		# Shuffle the replacement list so we don't always put mutants in the same IDs
		random.shuffle(to_replace_indices)

		# 3. Fill the replacement slots based on our budget
		current_idx = 0

		# --- Fill Mutants ---
		for _ in range(mutant_count):
			if current_idx >= len(to_replace_indices): break
			target_slot = to_replace_indices[current_idx]
			parent = self.population[random.choice(elite_indices)]
			self.population[target_slot] = self.__mutate(parent)
			current_idx += 1

		# --- Fill Crossovers ---
		for _ in range(crossover_count):
			if current_idx >= len(to_replace_indices): break
			target_slot = to_replace_indices[current_idx]
			p1, p2 = random.sample([self.population[index] for index in elite_indices], 2)
			self.population[target_slot] = self.__crossover(p1, p2)
			current_idx += 1

		# --- Fill Fresh (Diversity) ---
		# Any remaining slots in the 'to_replace' list become fresh individuals
		while current_idx < len(to_replace_indices):
			target_slot = to_replace_indices[current_idx]
			self.population[target_slot] = self.__build_individual()
			current_idx += 1

	def __quadratic(self, reward):
		"""Aggressive algorithm."""
		if self.episodes_seen < 5: return 1.0
		denominator = (self.max_seen - self.min_seen) + 1e-8
		normalized_error = (self.max_seen - reward) / denominator
		return max(0.1, min(1.0, normalized_error ** 2))

	def __full(self, reward):
		"""Full."""
		return 1.0

	def __fuzzylogic(self, reward):
		"""Fuzzy logic membership: high reward."""
		if len(self.reward_history) < 10: return 1.0

		# We define "Low" as the 20th percentile and "High" as the 90th percentile
		low_limit = np.percentile(self.reward_history, 20)
		high_limit = np.percentile(self.reward_history, 90)

		if reward >= high_limit: return 0.1
		if reward <= low_limit: return 1.0

		# Calculate membership (mu) within the dynamic range
		mu = (reward - low_limit) / (high_limit - low_limit + 1e-8)
		return 1.0 - (mu * 0.9)

	def __get_plasticity(self, reward):
		"""Modular dispatch to chosen algorithm using getattr."""
		plasticity_algorithm = self.plasticity_algorithm if self.learn else "zero"
		try:
			# Dynamically call the private method based on string name
			method_name = f"_ENAgent__{plasticity_algorithm}"
			method = getattr(self, method_name)
			return method(reward)
		except AttributeError:
			print(f"   [WARNING] ENA Agent Invalid plasticity algorithm: {self.plasticity_algorithm}")
			return 1.0 # Default to full if algorithm name is invalid

	def __get_trust_decay(self, reward):
		"""Modular dispatch for Trust Reset logic"""
		try:
			method_name = f"_ENAgent__{self.trust_algorithm}"
			method = getattr(self, method_name)
			return method(reward)
		except AttributeError:
			return 0.0 # Default to no reset

	def __mutate(self, parent):
		"""Mutation method"""
		child = self.__build_individual()
		child["model"].set_weights(parent["model"].get_weights())
		child["age"] = parent["age"]
		weights = child["model"].get_weights()
		new_weights = []
		for weight in weights:
			mask = np.random.random(weight.shape) < self.mutation_rate
			noise = np.random.normal(0, 0.1, weight.shape)
			weight[mask] += noise[mask]
			new_weights.append(weight)
		child["model"].set_weights(new_weights)
		return child

	def __reset_trust(self, factor=1.0):
		"""Reset trust"""
		for guy in self.population:
			guy["trust"] = (guy["trust"] * (1.0 - factor)) + (self.__get_dynamic_ref_trust() * factor)

	def __save_to_hof(self, individual, trust, z_score):
		"""Helper to create a deep copy for the archive"""
		backup = self.__build_individual()
		backup["id"] = individual["id"] # Keep original ID
		backup["induction_z_score"] = z_score
		backup["model"].set_weights(individual["model"].get_weights())
		backup["trust"] = trust
		self.hall_of_fame[individual["id"]] = backup

	def __update_hall_of_fame(self, winner, old_trust):
		"""Update Hall of Fame"""
		# --- STEP 0: MEMORY DECAY ("Age-of-Discovery") ---
		# Every time we try to update the HoF, the existing legends fade slightly.
		# This ensures that if a strategy is not being "re-validated", it eventually
		# becomes vulnerable to replacement.
		MEMORY_DECAY_RATE = 0.995  # Retain 99.5% of glory per check

		for h_id in self.hall_of_fame:
			# We decay the 'Genius Score', not the Trust.
			# This means the agent remembers how to play (Trust), but forgets
			# how 'special' that player was (Z-Score).
			self.hall_of_fame[h_id]["induction_z_score"] *= MEMORY_DECAY_RATE

		# --- STEP 1: CALCULATE CONTEXT & METRICS ---
		current_trusts = [guy["trust"] for guy in self.population]
		avg_trust = np.mean(current_trusts)
		std_trust = np.std(current_trusts) + 1e-8

		# Calculate "Genius" Score (Z-Score)
		current_z_score = (old_trust - avg_trust) / std_trust

		# Calculate Entry Threshold (Lower bar if Plasticity is high/Chaos)
		current_plasticity = self.plasticity_history[-1] if self.plasticity_history else 1.0
		z_score_required = 1.5 * (1.0 - (current_plasticity * 0.5))

		# Early Exit: If they aren't impressive enough relative to CURRENT peers
		if current_z_score < z_score_required:
				return

		ind_id = winner["id"]

		# --- STEP 2: CHECK FOR EXISTING ID ---
		# If this specific agent ID is already in HoF, just update stats
		if ind_id in self.hall_of_fame:
			if current_z_score > self.hall_of_fame[ind_id].get("induction_z_score", 0):
				self.hall_of_fame[ind_id]["trust"] = old_trust
				self.hall_of_fame[ind_id]["induction_z_score"] = current_z_score
			return

		# --- STEP 3: NICHE PROTECTION (Genetic Similarity) ---
		# Check if a "Strategic Twin" already exists in the HoF
		SIMILARITY_THRESHOLD = 0.95  # 95% similar weights = same species
		for hof_id, hof_record in self.hall_of_fame.items():
			similarity = self.__calculate_genetic_similarity(winner, hof_record)

			if similarity > SIMILARITY_THRESHOLD:
				# TWIN FOUND!
				# We compete ONLY against this specific twin, not the weakest link.
				# This protects unique niches from being overwritten by duplicates.

				existing_z = hof_record.get("induction_z_score", -99)
				if current_z_score > existing_z:
					print(f"   >>> UPGRADE: Replaced Twin {hof_id} (Z:{existing_z:.1f}) with {ind_id} (Z:{current_z_score:.1f})")
					del self.hall_of_fame[hof_id]
					self.__save_to_hof(winner, old_trust, current_z_score)
				else:
					# If the new guy isn't smarter than his twin, we discard him.
					# We do NOT let him challenge a different niche.
					pass
				return # Exit immediately after handling the twin interaction

		# --- STEP 4: OPEN SLOT INDUCTION ---
		# If no twin was found and we have space, welcome aboard!
		if len(self.hall_of_fame) < self.gladiator_amounts:
			print(f"   >>> NEW NICHE: Inducted Pioneer {ind_id} (Z:{current_z_score:.1f})")
			self.__save_to_hof(winner, old_trust, current_z_score)
			return

		# --- STEP 5: COMPETITIVE REPLACEMENT (Full HoF) ---
		# If we are here, the HoF is full AND this agent is a unique new species.
		# Now they have earned the right to challenge the globally weakest link.

		weakest_id = min(self.hall_of_fame, key=lambda k: self.hall_of_fame[k].get("induction_z_score", 0))
		weakest_z = self.hall_of_fame[weakest_id].get("induction_z_score", 0)

		if current_z_score > weakest_z:
			print(f"   >>> EVOLUTION: New Species {ind_id} (Z:{current_z_score:.1f}) outcompeted {weakest_id} (Z:{weakest_z:.1f})")
			del self.hall_of_fame[weakest_id]
			self.__save_to_hof(winner, old_trust, current_z_score)

	def __zero(self, reward):
		"""Zero"""
		return 0.0

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

def calculate_paper_metrics(histories, names, success_threshold=475.0, times=None):
	"""
	Calculates academic metrics including Reliability (Success Rate),
	Stability Gaps at environment switches, and dynamic environment detection.
	"""
	metrics = []
	for dataframe, name in zip(histories, names):
		# Dynamically find where environments change
		switches = dataframe[dataframe["env_id"].diff() != 0].index.tolist()

		# 1. Reliability Metric: % of episodes above mastery threshold
		total_episodes = len(dataframe)
		successes = len(dataframe[dataframe["score"] >= success_threshold])
		reliability = (successes / total_episodes) * 100

		# 2. Performance per Environment (Dynamic for any number of worlds)
		env_results = {}
		for env_id in dataframe["env_id"].unique():
			avg = dataframe[dataframe["env_id"] == env_id]["score"].mean()
			env_results[f"Env_{env_id} Avg"] = round(avg, 2)

		# 3. Stability Gap: Measures drop in performance exactly at the first switch
		stability_gap = 0
		if len(switches) > 1:
			first_switch = switches[1]
			# Compare average of 20 episodes before vs 20 episodes after switch
			pre = dataframe.iloc[max(0, first_switch-20):first_switch]["score"].mean()
			post = dataframe.iloc[first_switch:first_switch+20]["score"].mean()
			stability_gap = pre - post

		# 4. Efficiency: Total Score divided by Wall-Clock Time
		efficiency = 0
		if times and name in times and times[name] > 0:
			total_score = dataframe["score"].sum()
			efficiency = total_score / times[name]

		res = {
			"Agent": name,
			**env_results,
			"Reliability (%)": f"{round(reliability, 1)}%",
			"Stability Gap (↓)": round(stability_gap, 2),
		}
		if times:
			res["Efficiency (Score/s)"] = round(efficiency, 2)

		metrics.append(res)

	metrics_df = pd.DataFrame(metrics)
	print("\n--- ACADEMIC PERFORMANCE & RELIABILITY SUMMARY ---")
	print(metrics_df.to_string(index=False))
	return metrics_df

def plot_academic_comparison(histories, names):
	"""
	Creates a publication-quality plot with stability ranges (Std Dev)
	and dynamic environment switch markers.
	"""
	fig, axs = plt.subplots(len(histories), 1, figsize=(15, 14), sharex=True)
	window = 50

	for index, dataframe in enumerate(histories):
		# Calculate Moving Stats
		mean_score = dataframe['score'].rolling(window=window, min_periods=1).mean()
		std_score = dataframe['score'].rolling(window=window, min_periods=1).std()

		# Shaded area = Reliability / Variance
		axs[index].fill_between(
			dataframe['episode'],
			mean_score - std_score,
			mean_score + std_score,
			alpha=0.2, color='tab:blue', label='Stability Range'
		)

		# Bold line = Average Trend
		axs[index].plot(dataframe['episode'], mean_score, color='tab:blue', linewidth=3, label='Mean Performance')

		# Mastery Threshold line (475)
		axs[index].axhline(y=475, color='green', linestyle=':', alpha=0.5, label='Mastery (475)')

		# Dynamic Environment Switches
		switches = dataframe[dataframe['env_id'].diff() != 0].index.tolist()
		for s_idx in switches:
			if s_idx > 0:
				axs[index].axvline(x=s_idx, color='red', linestyle='--', linewidth=2, alpha=0.7)
				if index == 0: # Only label the top plot to keep it clean
					axs[index].text(s_idx + 5, 450, 'ENV SWITCH', color='red', fontweight='bold')

		axs[index].set_ylabel('Score', fontsize=12)
		axs[index].set_ylim(-10, 550)
		axs[index].set_title(f'Agent: {names[index]}', loc='left', fontsize=14, fontweight='bold')
		axs[index].grid(True, alpha=0.2)
		axs[index].legend(loc='upper left')

	plt.suptitle('Neuroevolutionary Adaptation\nAcross Gravitational Shifts', fontsize=16)
	plt.xlabel('Total Episodes', fontsize=12)
	plt.tight_layout(rect=[0, 0.03, 1, 0.95])
	plt.savefig('academic_results.png', dpi=300)
	plt.show()

def plot_plasticity_analysis(agent, history_df):
	fig, ax1 = plt.subplots(figsize=(12, 6))
	color_score, color_plast = 'tab:blue', 'tab:orange'

	# 1. Plot Score
	ax1.set_xlabel('Total Episodes')
	ax1.set_ylabel('Score', color=color_score)
	ax1.plot(history_df['episode'], history_df['score'], alpha=0.15, color=color_score)
	ax1.plot(history_df['episode'], history_df['score'].rolling(window=20).mean(), color=color_score, linewidth=2)
	ax1.tick_params(axis='y', labelcolor=color_score)

	# 2. Align Plasticity Data
	# Since plasticity only records during training, we pad it for the test phase
	plast_data = list(agent.plasticity_history)
	if len(plast_data) < len(history_df):
		# Fill the "Zero-Shot" gap with 0.0 plasticity (since no search happened)
		plast_data.extend([0.0] * (len(history_df) - len(plast_data)))

	ax2 = ax1.twinx()
	ax2.set_ylabel('Plasticity (Search Effort)', color=color_plast)
	ax2.plot(history_df['episode'], plast_data[:len(history_df)], color=color_plast, linewidth=2, alpha=0.8)
	ax2.fill_between(history_df['episode'], 0, plast_data[:len(history_df)], color=color_plast, alpha=0.1)
	ax2.set_ylim(0, 1.1)

	plt.title('ENA Resource Allocation: Performance vs. Search Effort')
	plt.show()

def plot_specialist_transitions(df_history, pop_size=30):
	# 1. Increase height to (14, 8) to give more vertical room for IDs
	fig, ax1 = plt.subplots(figsize=(14, 8))

	# Color background by environment
	unique_envs = df_history['env_id'].unique()
	colors = ['gray', 'orange', 'blue', 'red'] # Earth, Mars, Neptune, Jupiter

	for i, env_id in enumerate(unique_envs):
		mask = df_history['env_id'] == env_id
		if not mask.any(): continue

		start, end = df_history[mask]['episode'].min(), df_history[mask]['episode'].max()
		ax1.axvspan(start, end, alpha=0.07, color=colors[i % len(colors)])

		# 2. Position text dynamically at the very top of the limit
		ax1.text((start+end)/2, pop_size + 0.2, f"Env {env_id}",
				 ha='center', fontweight='bold', alpha=0.6, fontsize=12)

	# 3. Adjust scatter size 's' slightly down to prevent overlap
	sns.scatterplot(
		data=df_history,
		x='episode',
		y='specialist_id',
		hue='specialist_id',
		palette='tab20', # High contrast for many IDs
		ax=ax1,
		s=20,
		alpha=0.7,
		legend=False,
	)

	ax1.set_ylabel('Active Specialist ID', fontweight='bold')
	ax1.set_xlabel('Episode', fontweight='bold')

	# 4. FIXED: Set ticks to show every individual ID for pop_size <= 50
	# If pop_size is very large, use range(0, pop_size + 1, 5)
	tick_step = 1 if pop_size <= 40 else 5
	ax1.set_yticks(range(0, pop_size, tick_step))

	ax1.set_ylim(-0.5, pop_size + 1) # Extra room at top for labels
	ax1.grid(True, axis='y', alpha=0.2, linestyle='--') # Emphasize horizontal lines

	plt.title('ENA Behavioral Switching: Selection vs Gravitational Regime', pad=20, fontsize=14)
	plt.tight_layout()
	plt.show()

# General imports
import time

# Libs imports
import pandas as pd
import numpy as np

def run_independent_experiment(experiment_id):
	"""
	Runs one complete independent experiment (training + testing) for all
	three ENA configurations. Called 10 times to produce n=10 statistical
	replications as reported in the paper. Each call creates fresh agent
	instances with their own random population initializations, ensuring
	full independence between runs.
	"""
	print(f"\n{'='*20} RUNNING EXPERIMENT {experiment_id + 1}/10 {'='*20}")

	# 1. Prepare Environments
	worlds = [
		make_env(gravity=9.8),   # Earth
		make_env(gravity=3.7),   # Mars
		make_env(gravity=24.8),  # Jupiter
	]

	# Define explicit episode counts (250 episodes per training environment)
	ena_training_episodes = [250, 250, 250]
	execution_times = {}

	# 2. Initialize Agents — fresh instances per experiment for independence
	print("  Initializing Agents...")
	ena_agent_01 = ENAgent(
		action_size=2,
		state_shape=(4,),
		plasticity_algorithm="fuzzylogic",
		pop_size=20,
		trust_algorithm="fuzzylogic",
	)

	ena_agent_02 = ENAgent(
		action_size=2,
		state_shape=(4,),
		plasticity_algorithm="quadratic",
		pop_size=20,
		trust_algorithm="quadratic",
	)

	# 3. Training Phase
	# --- ENA-01: Fuzzy-logic ---
	print("  Training ENA-01 (Fuzzy-logic)...")
	ena_agent_01.set_learning(True)
	start_time = time.time()
	history_ena_01 = play(ena_agent_01, worlds, ena_training_episodes)
	execution_times["ENA-01"] = time.time() - start_time

	# --- ENA-02: Quadratic Ratio ---
	print("  Training ENA-02 (Quadratic Ratio)...")
	ena_agent_02.set_learning(True)
	start_time = time.time()
	history_ena_02 = play(ena_agent_02, worlds, ena_training_episodes)
	execution_times["ENA-02"] = time.time() - start_time

	# 4. Training Summary
	print("\n  --- Training Performance vs Time ---")
	for agent_name, duration in execution_times.items():
		print(f"  {agent_name}: {duration:.2f} seconds")

	# 5. Phase 2: Testing (frozen policies, online meta-adaptation)
	# Neural weights are frozen; only the archive selector updates Trust at test time.
	mystery_env = make_env(gravity=11.15)  # Neptune — withheld from training
	test_worlds = [worlds[0], worlds[1], worlds[2], mystery_env]
	test_episodes = [250, 250, 250, 250]

	# Load Hall of Fame gladiators into the active population before testing
	ena_agent_01.set_learning(False)
	ena_agent_01.load_gladiators()
	ena_agent_02.set_learning(False)
	ena_agent_02.load_gladiators()

	print("\n  Running Phase 2: Testing...")

	print("  ENA-01...")
	history_test_ena_01 = play(ena_agent_01, test_worlds, test_episodes)

	print("  ENA-02...")
	history_test_ena_02 = play(ena_agent_02, test_worlds, test_episodes)

	# ENA-03: Uses the Fuzzy-trained HoF archive but switches to Quadratic Trust during testing
	print("  ENA-03 (Fuzzy HoF + Quadratic Trust)...")
	ena_agent_01.set_learning(False)
	ena_agent_01.trust_algorithm = "quadratic"
	history_test_ena_03 = play(ena_agent_01, test_worlds, test_episodes)

	histories = [history_test_ena_01, history_test_ena_02, history_test_ena_03]
	names = ["ENA-01", "ENA-02", "ENA-03"]

	# 6. Calculate and print metrics for this experiment
	print(f"\n  --- Experiment {experiment_id + 1} Test Results ---")
	test_metrics = calculate_paper_metrics(
		histories,
		names,
		success_threshold=495.0
	)

	return test_metrics


# =============================================================================
# MAIN: Run 10 independent experiments to produce statistically valid results
# as reported in Table I and Figure 4 of the paper.
# =============================================================================
if __name__ == "__main__":
	all_experiment_results = []
	for exp_id in range(10):
		result = run_independent_experiment(exp_id)
		all_experiment_results.append(result)
	print("\n" + "="*60)
	print("ALL 10 EXPERIMENTS COMPLETE")
	print("Aggregate the 'all_experiment_results' list to reproduce")
	print("the mean/std statistics reported in Table I of the paper.")
	print("="*60)
